"""empty message

Revision ID: 39d3f262ac75
Revises: ac946c28394f
Create Date: 2021-08-26 22:00:11.159085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39d3f262ac75'
down_revision = 'ac946c28394f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'certified_by',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('certificates', 'certified_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('projects', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('projects', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('certificates', 'certified_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('certificates', 'certified_by',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
