"""empty message

Revision ID: 51c2dfc8436c
Revises: 39d3f262ac75
Create Date: 2021-08-27 01:57:45.148416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51c2dfc8436c'
down_revision = '39d3f262ac75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.alter_column('projects', 'start_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('projects', 'end_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'end_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_table('profiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_image', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('introduction', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profiles_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
