"""empty message

Revision ID: 6f81531e4c23
Revises: 3aa6092b19fb
Create Date: 2021-08-22 20:41:56.606024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f81531e4c23'
down_revision = '3aa6092b19fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'name')
    op.drop_column('profiles', 'mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('mimetype', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('profiles', sa.Column('name', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    # ### end Alembic commands ###
