"""empty message

Revision ID: 8499272edea0
Revises: bf8b53dc8b93
Create Date: 2021-08-16 22:20:05.564330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8499272edea0'
down_revision = 'bf8b53dc8b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('userid', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('userid', 'user', ['userid'], unique=False)
    # ### end Alembic commands ###
