"""empty message

Revision ID: 8e0ca540b627
Revises: 60451d6d07aa
Create Date: 2021-08-18 14:11:10.997034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e0ca540b627'
down_revision = '60451d6d07aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('Profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_username', sa.String(length=32), nullable=False),
    sa.Column('profile_image', sa.String(length=100), nullable=True),
    sa.Column('introduction', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('userid', table_name='User')
    op.drop_table('User')
    op.drop_constraint('awards_ibfk_1', 'Awards', type_='foreignkey')
    op.create_foreign_key(None, 'Awards', 'user', ['user_id'], ['id'])
    op.drop_constraint('certificates_ibfk_1', 'Certificates', type_='foreignkey')
    op.create_foreign_key(None, 'Certificates', 'user', ['user_id'], ['id'])
    op.drop_constraint('education_ibfk_1', 'Education', type_='foreignkey')
    op.create_foreign_key(None, 'Education', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Education', type_='foreignkey')
    op.create_foreign_key('education_ibfk_1', 'Education', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'Certificates', type_='foreignkey')
    op.create_foreign_key('certificates_ibfk_1', 'Certificates', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'Awards', type_='foreignkey')
    op.create_foreign_key('awards_ibfk_1', 'Awards', 'User', ['user_id'], ['id'])
    op.create_table('User',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('userid', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('userid', 'User', ['userid'], unique=False)
    op.drop_table('Projects')
    op.drop_table('Profile')
    op.drop_table('user')
    # ### end Alembic commands ###
