"""empty message

Revision ID: ca6acdbb249b
Revises: 6f81531e4c23
Create Date: 2021-08-24 16:54:21.982142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6acdbb249b'
down_revision = '6f81531e4c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('introduction', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
