"""empty message

Revision ID: cb30595f3fab
Revises: ca6acdbb249b
Create Date: 2021-08-24 21:24:23.936172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb30595f3fab'
down_revision = 'ca6acdbb249b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('awards_ibfk_1', 'awards', type_='foreignkey')
    op.create_foreign_key(None, 'awards', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('certificates_ibfk_1', 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('educations_ibfk_1', 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profiles_ibfk_1', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('projects_ibfk_1', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_ibfk_1', 'projects', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_ibfk_1', 'profiles', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key('educations_ibfk_1', 'educations', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key('certificates_ibfk_1', 'certificates', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.create_foreign_key('awards_ibfk_1', 'awards', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
