"""empty message

Revision ID: f80fcbf8ad4a
Revises: fec0a50f7378
Create Date: 2021-08-22 02:42:34.845008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80fcbf8ad4a'
down_revision = 'fec0a50f7378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('profiles', sa.Column('mimetype', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'mimetype')
    op.drop_column('profiles', 'name')
    # ### end Alembic commands ###
