"""empty message

Revision ID: fec0a50f7378
Revises: 324ba09d5890
Create Date: 2021-08-21 19:19:38.534177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fec0a50f7378'
down_revision = '324ba09d5890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('awards', 'awards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('awards', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('awards', 'name')
    # ### end Alembic commands ###
